// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export const schema = "prisma/schema.prisma";
export const migrations = "prisma/migrations";
